// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include "djinni_support.hpp"
#include "http_request_gen.hpp"

namespace djinni_generated {

class NativeHttpRequestGen final : ::djinni::JniInterface<::gearsbox::HttpRequestGen, NativeHttpRequestGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::HttpRequestGen>;
    using CppOptType = std::shared_ptr<::gearsbox::HttpRequestGen>;
    using JniType = jobject;

    using Boxed = NativeHttpRequestGen;

    ~NativeHttpRequestGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeHttpRequestGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeHttpRequestGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeHttpRequestGen();
    friend ::djinni::JniClass<NativeHttpRequestGen>;
    friend ::djinni::JniInterface<::gearsbox::HttpRequestGen, NativeHttpRequestGen>;

};

}  // namespace djinni_generated
