// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include "async_loop_gen.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAsyncLoopGen final : ::djinni::JniInterface<::gearsbox::AsyncLoopGen, NativeAsyncLoopGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::AsyncLoopGen>;
    using CppOptType = std::shared_ptr<::gearsbox::AsyncLoopGen>;
    using JniType = jobject;

    using Boxed = NativeAsyncLoopGen;

    ~NativeAsyncLoopGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAsyncLoopGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAsyncLoopGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAsyncLoopGen();
    friend ::djinni::JniClass<NativeAsyncLoopGen>;
    friend ::djinni::JniInterface<::gearsbox::AsyncLoopGen, NativeAsyncLoopGen>;

};

}  // namespace djinni_generated
