// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "NativeCallbackHttpGen.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeCallbackHttpGen::NativeCallbackHttpGen() : ::djinni::JniInterface<::gearsbox::CallbackHttpGen, NativeCallbackHttpGen>() {}

NativeCallbackHttpGen::~NativeCallbackHttpGen() = default;

NativeCallbackHttpGen::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeCallbackHttpGen::JavaProxy::~JavaProxy() = default;

bool NativeCallbackHttpGen::JavaProxy::callback(int64_t c_id, bool c_result, const std::string & c_data) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeCallbackHttpGen>::get();
    auto jret = jniEnv->CallBooleanMethod(Handle::get().get(), data.method_callback,
                                          ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_id)),
                                          ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c_result)),
                                          ::djinni::get(::djinni::String::fromCpp(jniEnv, c_data)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::Bool::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
