// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "djinni_support.hpp"
#include "ui_injecter_gen.hpp"

namespace djinni_generated {

class NativeUiInjecterGen final : ::djinni::JniInterface<::gearsbox::UiInjecterGen, NativeUiInjecterGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::UiInjecterGen>;
    using CppOptType = std::shared_ptr<::gearsbox::UiInjecterGen>;
    using JniType = jobject;

    using Boxed = NativeUiInjecterGen;

    ~NativeUiInjecterGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeUiInjecterGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeUiInjecterGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeUiInjecterGen();
    friend ::djinni::JniClass<NativeUiInjecterGen>;
    friend ::djinni::JniInterface<::gearsbox::UiInjecterGen, NativeUiInjecterGen>;

};

}  // namespace djinni_generated
