// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "NativeHttpRequestGen.hpp"  // my header
#include "Marshal.hpp"
#include "NativeCallbackHttpGen.hpp"
#include "NativeHttpRequestGen.hpp"

namespace djinni_generated {

NativeHttpRequestGen::NativeHttpRequestGen() : ::djinni::JniInterface<::gearsbox::HttpRequestGen, NativeHttpRequestGen>("dyno/fun/gearsbox/HttpRequestGen$CppProxy") {}

NativeHttpRequestGen::~NativeHttpRequestGen() = default;


CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_HttpRequestGen_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::gearsbox::HttpRequestGen>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_dyno_fun_gearsbox_HttpRequestGen_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::gearsbox::HttpRequestGen::create();
        return ::djinni::release(::djinni_generated::NativeHttpRequestGen::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jlong JNICALL Java_dyno_fun_gearsbox_HttpRequestGen_00024CppProxy_native_1get(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_url, jobject j_callback)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::HttpRequestGen>(nativeRef);
        auto r = ref->get(::djinni::String::toCpp(jniEnv, j_url),
                          ::djinni_generated::NativeCallbackHttpGen::toCpp(jniEnv, j_callback));
        return ::djinni::release(::djinni::I64::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
