// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "NativeViewEventHandler.hpp"  // my header
#include "Marshal.hpp"
#include "NativeViewEventParam.hpp"
#include "NativeViewGen.hpp"

namespace djinni_generated {

NativeViewEventHandler::NativeViewEventHandler() : ::djinni::JniInterface<::gearsbox::ViewEventHandler, NativeViewEventHandler>("dyno/fun/gearsbox/ViewEventHandler$CppProxy") {}

NativeViewEventHandler::~NativeViewEventHandler() = default;


CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_ViewEventHandler_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::gearsbox::ViewEventHandler>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jboolean JNICALL Java_dyno_fun_gearsbox_ViewEventHandler_00024CppProxy_native_1handle(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_param, jobject j_view)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::ViewEventHandler>(nativeRef);
        auto r = ref->handle(::djinni_generated::NativeViewEventParam::toCpp(jniEnv, j_param),
                             ::djinni_generated::NativeViewGen::toCpp(jniEnv, j_view));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
