// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "djinni_support.hpp"
#include "view_event.hpp"

namespace djinni_generated {

class NativeViewEvent final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::ViewEvent;
    using JniType = jobject;

    using Boxed = NativeViewEvent;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeViewEvent>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeViewEvent>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeViewEvent() : JniEnum("dyno/fun/gearsbox/ViewEvent") {}
    friend ::djinni::JniClass<NativeViewEvent>;
};

}  // namespace djinni_generated
