// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "djinni_support.hpp"
#include "view_event_param.hpp"

namespace djinni_generated {

class NativeViewEventParam final {
public:
    using CppType = ::gearsbox::ViewEventParam;
    using JniType = jobject;

    using Boxed = NativeViewEventParam;

    ~NativeViewEventParam();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeViewEventParam();
    friend ::djinni::JniClass<NativeViewEventParam>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("dyno/fun/gearsbox/ViewEventParam") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(FFLdyno/fun/gearsbox/ViewEvent;Ljava/lang/String;)V") };
    const jfieldID field_mX { ::djinni::jniGetFieldID(clazz.get(), "mX", "F") };
    const jfieldID field_mY { ::djinni::jniGetFieldID(clazz.get(), "mY", "F") };
    const jfieldID field_mType { ::djinni::jniGetFieldID(clazz.get(), "mType", "Ldyno/fun/gearsbox/ViewEvent;") };
    const jfieldID field_mText { ::djinni::jniGetFieldID(clazz.get(), "mText", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
