// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "NativeViewGen.hpp"  // my header
#include "Marshal.hpp"
#include "NativeViewConstraint.hpp"
#include "NativeViewFrame.hpp"
#include "NativeViewGen.hpp"

namespace djinni_generated {

NativeViewGen::NativeViewGen() : ::djinni::JniInterface<::gearsbox::ViewGen, NativeViewGen>() {}

NativeViewGen::~NativeViewGen() = default;

NativeViewGen::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeViewGen::JavaProxy::~JavaProxy() = default;

void NativeViewGen::JavaProxy::setFrame(const ::gearsbox::ViewFrame & c_frame) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeViewGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setFrame,
                           ::djinni::get(::djinni_generated::NativeViewFrame::fromCpp(jniEnv, c_frame)));
    ::djinni::jniExceptionCheck(jniEnv);
}
::gearsbox::ViewFrame NativeViewGen::JavaProxy::getFrame() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeViewGen>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_getFrame);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::NativeViewFrame::toCpp(jniEnv, jret);
}
void NativeViewGen::JavaProxy::setVisiable(bool c_v) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeViewGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setVisiable,
                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c_v)));
    ::djinni::jniExceptionCheck(jniEnv);
}
bool NativeViewGen::JavaProxy::addSubView(const std::shared_ptr<::gearsbox::ViewGen> & c_view) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeViewGen>::get();
    auto jret = jniEnv->CallBooleanMethod(Handle::get().get(), data.method_addSubView,
                                          ::djinni::get(::djinni_generated::NativeViewGen::fromCpp(jniEnv, c_view)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::Bool::toCpp(jniEnv, jret);
}
void NativeViewGen::JavaProxy::addConstraint(const ::gearsbox::ViewConstraint & c_constraint) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeViewGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_addConstraint,
                           ::djinni::get(::djinni_generated::NativeViewConstraint::fromCpp(jniEnv, c_constraint)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
