// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "NativeViewGroupGen.hpp"  // my header
#include "Marshal.hpp"
#include "NativeViewGen.hpp"

namespace djinni_generated {

NativeViewGroupGen::NativeViewGroupGen() : ::djinni::JniInterface<::gearsbox::ViewGroupGen, NativeViewGroupGen>() {}

NativeViewGroupGen::~NativeViewGroupGen() = default;

NativeViewGroupGen::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeViewGroupGen::JavaProxy::~JavaProxy() = default;

std::shared_ptr<::gearsbox::ViewGen> NativeViewGroupGen::JavaProxy::getView(const std::string & c_id) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeViewGroupGen>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_getView,
                                         ::djinni::get(::djinni::String::fromCpp(jniEnv, c_id)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::NativeViewGen::toCpp(jniEnv, jret);
}
bool NativeViewGroupGen::JavaProxy::addView(const std::shared_ptr<::gearsbox::ViewGen> & c_view) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeViewGroupGen>::get();
    auto jret = jniEnv->CallBooleanMethod(Handle::get().get(), data.method_addView,
                                          ::djinni::get(::djinni_generated::NativeViewGen::fromCpp(jniEnv, c_view)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::Bool::toCpp(jniEnv, jret);
}
bool NativeViewGroupGen::JavaProxy::removeView(const std::shared_ptr<::gearsbox::ViewGen> & c_view) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeViewGroupGen>::get();
    auto jret = jniEnv->CallBooleanMethod(Handle::get().get(), data.method_removeView,
                                          ::djinni::get(::djinni_generated::NativeViewGen::fromCpp(jniEnv, c_view)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::Bool::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
