// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "djinni_support.hpp"
#include "view_type.hpp"

namespace djinni_generated {

class NativeViewType final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::ViewType;
    using JniType = jobject;

    using Boxed = NativeViewType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeViewType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeViewType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeViewType() : JniEnum("dyno/fun/gearsbox/ViewType") {}
    friend ::djinni::JniClass<NativeViewType>;
};

}  // namespace djinni_generated
