// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "djinni_support.hpp"
#include "view_event_handler.hpp"

namespace djinni_generated {

class NativeViewEventHandler final : ::djinni::JniInterface<::gearsbox::ViewEventHandler, NativeViewEventHandler> {
public:
    using CppType = std::shared_ptr<::gearsbox::ViewEventHandler>;
    using CppOptType = std::shared_ptr<::gearsbox::ViewEventHandler>;
    using JniType = jobject;

    using Boxed = NativeViewEventHandler;

    ~NativeViewEventHandler();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeViewEventHandler>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeViewEventHandler>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeViewEventHandler();
    friend ::djinni::JniClass<NativeViewEventHandler>;
    friend ::djinni::JniInterface<::gearsbox::ViewEventHandler, NativeViewEventHandler>;

};

}  // namespace djinni_generated
