// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "NativeViewFactoryGen.hpp"  // my header
#include "Marshal.hpp"
#include "NativeViewGen.hpp"
#include "NativeViewType.hpp"

namespace djinni_generated {

NativeViewFactoryGen::NativeViewFactoryGen() : ::djinni::JniInterface<::gearsbox::ViewFactoryGen, NativeViewFactoryGen>() {}

NativeViewFactoryGen::~NativeViewFactoryGen() = default;

NativeViewFactoryGen::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeViewFactoryGen::JavaProxy::~JavaProxy() = default;

std::shared_ptr<::gearsbox::ViewGen> NativeViewFactoryGen::JavaProxy::createView(const std::string & c_id, ::gearsbox::ViewType c_type) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeViewFactoryGen>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_createView,
                                         ::djinni::get(::djinni::String::fromCpp(jniEnv, c_id)),
                                         ::djinni::get(::djinni_generated::NativeViewType::fromCpp(jniEnv, c_type)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::NativeViewGen::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
