// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class AsyncLoopGen {
    public abstract void process(long elapse);

    public static native AsyncLoopGen instance();

    private static final class CppProxy extends AsyncLoopGen
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void process(long elapse)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_process(this.nativeRef, elapse);
        }
        private native void native_process(long _nativeRef, long elapse);
    }
}
