// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

public abstract class CallbackHttpGen {
    public abstract boolean callback(long id, boolean result, String data);
}
