// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public enum ConstraintType {
    NONE,
    LEADING,
    TRAILING,
    TOP,
    BOTTOM,
    WIDTH,
    HEIGHT,
    CENTERX,
    CENTERY,
    ;
}
