// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class UiInjecterGen {
    public abstract void inject(String id, ViewGen view);

    public abstract ViewGen getView(String id);

    public abstract void removeView(String id);

    public static native UiInjecterGen instance();

    private static final class CppProxy extends UiInjecterGen
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void inject(String id, ViewGen view)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_inject(this.nativeRef, id, view);
        }
        private native void native_inject(long _nativeRef, String id, ViewGen view);

        @Override
        public ViewGen getView(String id)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getView(this.nativeRef, id);
        }
        private native ViewGen native_getView(long _nativeRef, String id);

        @Override
        public void removeView(String id)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_removeView(this.nativeRef, id);
        }
        private native void native_removeView(long _nativeRef, String id);
    }
}
