// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public enum ViewType {
    VIEW_BASE,
    VIEW_LABEL,
    VIEW_INPUT,
    VIEW_BTN,
    ;
}
