// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public abstract class ViewGen {
    public abstract void setFrame(ViewFrame frame);

    public abstract ViewFrame getFrame();

    public abstract void setVisiable(boolean v);

    public abstract boolean addSubView(ViewGen view);

    public abstract void addConstraint(ViewConstraint constraint);
}
