// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public final class ViewFrame {


    /*package*/ final float mX;

    /*package*/ final float mY;

    /*package*/ final float mW;

    /*package*/ final float mH;

    public ViewFrame(
            float x,
            float y,
            float w,
            float h) {
        this.mX = x;
        this.mY = y;
        this.mW = w;
        this.mH = h;
    }

    public float getX() {
        return mX;
    }

    public float getY() {
        return mY;
    }

    public float getW() {
        return mW;
    }

    public float getH() {
        return mH;
    }

    @Override
    public String toString() {
        return "ViewFrame{" +
                "mX=" + mX +
                "," + "mY=" + mY +
                "," + "mW=" + mW +
                "," + "mH=" + mH +
        "}";
    }

}
