// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public abstract class ViewGen {
    public abstract String getId();

    public abstract void setFrame(ViewFrame frame);

    public abstract ViewFrame getFrame();

    public abstract void setBackgroundColor(float a, float r, float g, float b);

    public abstract void setVisiable(boolean v);
}
