// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public abstract class ViewFactoryGen {
    public abstract ViewGen createView(String id, ViewType type);
}
