// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ViewEventHandler {
    public abstract boolean handle(ViewEventParam param, ViewGen view);

    private static final class CppProxy extends ViewEventHandler
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public boolean handle(ViewEventParam param, ViewGen view)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_handle(this.nativeRef, param, view);
        }
        private native boolean native_handle(long _nativeRef, ViewEventParam param, ViewGen view);
    }
}
