// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public enum ViewEvent {
    EVENT_NONE,
    EVENT_TAP,
    EVENT_TEXT_CHANGED,
    EVENT_BTN,
    ;
}
