// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public abstract class ViewGroupGen {
    public abstract ViewGen getView(String id);

    public abstract boolean addView(ViewGen view);

    public abstract boolean removeView(ViewGen view);
}
