// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public final class ViewEventParam {


    /*package*/ final float mX;

    /*package*/ final float mY;

    /*package*/ final ViewEvent mType;

    /*package*/ final String mText;

    public ViewEventParam(
            float x,
            float y,
            ViewEvent type,
            String text) {
        this.mX = x;
        this.mY = y;
        this.mType = type;
        this.mText = text;
    }

    public float getX() {
        return mX;
    }

    public float getY() {
        return mY;
    }

    public ViewEvent getType() {
        return mType;
    }

    public String getText() {
        return mText;
    }

    @Override
    public String toString() {
        return "ViewEventParam{" +
                "mX=" + mX +
                "," + "mY=" + mY +
                "," + "mType=" + mType +
                "," + "mText=" + mText +
        "}";
    }

}
