// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public final class ViewConstraint {

    public static final String PARENT = "parent";


    /*package*/ final ConstraintType mType;

    /*package*/ final ConstraintType mTypeTo;

    /*package*/ final String mViewFrom;

    /*package*/ final String mViewTo;

    /*package*/ final float mMultiplier;

    /*package*/ final float mOffset;

    public ViewConstraint(
            ConstraintType type,
            ConstraintType typeTo,
            String viewFrom,
            String viewTo,
            float multiplier,
            float offset) {
        this.mType = type;
        this.mTypeTo = typeTo;
        this.mViewFrom = viewFrom;
        this.mViewTo = viewTo;
        this.mMultiplier = multiplier;
        this.mOffset = offset;
    }

    public ConstraintType getType() {
        return mType;
    }

    public ConstraintType getTypeTo() {
        return mTypeTo;
    }

    public String getViewFrom() {
        return mViewFrom;
    }

    public String getViewTo() {
        return mViewTo;
    }

    public float getMultiplier() {
        return mMultiplier;
    }

    public float getOffset() {
        return mOffset;
    }

    @Override
    public String toString() {
        return "ViewConstraint{" +
                "mType=" + mType +
                "," + "mTypeTo=" + mTypeTo +
                "," + "mViewFrom=" + mViewFrom +
                "," + "mViewTo=" + mViewTo +
                "," + "mMultiplier=" + mMultiplier +
                "," + "mOffset=" + mOffset +
        "}";
    }

}
