// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public final class ViewConstraint {


    /*package*/ final ConstraintType mType;

    /*package*/ final String mViewFrom;

    /*package*/ final String mViewTo;

    /*package*/ final int mMultiplier;

    /*package*/ final int mOffset;

    public ViewConstraint(
            ConstraintType type,
            String viewFrom,
            String viewTo,
            int multiplier,
            int offset) {
        this.mType = type;
        this.mViewFrom = viewFrom;
        this.mViewTo = viewTo;
        this.mMultiplier = multiplier;
        this.mOffset = offset;
    }

    public ConstraintType getType() {
        return mType;
    }

    public String getViewFrom() {
        return mViewFrom;
    }

    public String getViewTo() {
        return mViewTo;
    }

    public int getMultiplier() {
        return mMultiplier;
    }

    public int getOffset() {
        return mOffset;
    }

    @Override
    public String toString() {
        return "ViewConstraint{" +
                "mType=" + mType +
                "," + "mViewFrom=" + mViewFrom +
                "," + "mViewTo=" + mViewTo +
                "," + "mMultiplier=" + mMultiplier +
                "," + "mOffset=" + mOffset +
        "}";
    }

}
