// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public final class ViewFrame {


    /*package*/ final int mX;

    /*package*/ final int mY;

    /*package*/ final int mW;

    /*package*/ final int mH;

    public ViewFrame(
            int x,
            int y,
            int w,
            int h) {
        this.mX = x;
        this.mY = y;
        this.mW = w;
        this.mH = h;
    }

    public int getX() {
        return mX;
    }

    public int getY() {
        return mY;
    }

    public int getW() {
        return mW;
    }

    public int getH() {
        return mH;
    }

    @Override
    public String toString() {
        return "ViewFrame{" +
                "mX=" + mX +
                "," + "mY=" + mY +
                "," + "mW=" + mW +
                "," + "mH=" + mH +
        "}";
    }

}
