// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "async_loop_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBAsyncLoopGen;

namespace djinni_generated {

class AsyncLoopGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::AsyncLoopGen>;
    using CppOptType = std::shared_ptr<::gearsbox::AsyncLoopGen>;
    using ObjcType = GBAsyncLoopGen*;

    using Boxed = AsyncLoopGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

