// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@class GBAsyncLoopGen;


@interface GBAsyncLoopGen : NSObject

+ (nullable GBAsyncLoopGen *)instance;

- (void)process:(int64_t)elapse;

@end
