// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>


@protocol GBCallbackHttpGen

- (BOOL)callback:(int64_t)id
          result:(BOOL)result
            data:(nonnull NSString *)data;

@end
