// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "callback_http_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol GBCallbackHttpGen;

namespace djinni_generated {

class CallbackHttpGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::CallbackHttpGen>;
    using CppOptType = std::shared_ptr<::gearsbox::CallbackHttpGen>;
    using ObjcType = id<GBCallbackHttpGen>;

    using Boxed = CallbackHttpGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

