// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, GBConstraintType)
{
    GBConstraintTypeLeading,
    GBConstraintTypeTrailing,
    GBConstraintTypeTop,
    GBConstraintTypeBottom,
    GBConstraintTypeWidth,
    GBConstraintTypeHeight,
    GBConstraintTypeCenterX,
    GBConstraintTypeCenterY,
};
