// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@class GBHttpRequestGen;
@protocol GBCallbackHttpGen;


@interface GBHttpRequestGen : NSObject

+ (nullable GBHttpRequestGen *)create;

- (int64_t)get:(nonnull NSString *)url
      callback:(nullable id<GBCallbackHttpGen>)callback;

@end
