// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "http_request_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBHttpRequestGen;

namespace djinni_generated {

class HttpRequestGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::HttpRequestGen>;
    using CppOptType = std::shared_ptr<::gearsbox::HttpRequestGen>;
    using ObjcType = GBHttpRequestGen*;

    using Boxed = HttpRequestGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

