// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBLogGen.h"


int32_t const GBLogGenLOGCONSOLE = 1;

int32_t const GBLogGenLOGFILE = 2;

int32_t const GBLogGenLOGNET = 4;

int32_t const GBLogGenLOGVERBOSE = 1;

int32_t const GBLogGenLOGDEBUG = 2;

int32_t const GBLogGenLOGINFO = 3;

int32_t const GBLogGenLOGWARN = 4;

int32_t const GBLogGenLOGERROR = 5;

int32_t const GBLogGenLOGFATAL = 6;
