// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@class GBLogGen;

extern int32_t const GBLogGenLOGCONSOLE;
extern int32_t const GBLogGenLOGFILE;
extern int32_t const GBLogGenLOGNET;
extern int32_t const GBLogGenLOGVERBOSE;
extern int32_t const GBLogGenLOGDEBUG;
extern int32_t const GBLogGenLOGINFO;
extern int32_t const GBLogGenLOGWARN;
extern int32_t const GBLogGenLOGERROR;
extern int32_t const GBLogGenLOGFATAL;

@interface GBLogGen : NSObject

+ (nullable GBLogGen *)instance;

- (BOOL)initialize:(int32_t)output
             param:(nonnull NSString *)param;

- (void)log:(int32_t)output
        lev:(int32_t)lev
        msg:(nonnull NSString *)msg;

@end
