// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "log_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBLogGen;

namespace djinni_generated {

class LogGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::LogGen>;
    using CppOptType = std::shared_ptr<::gearsbox::LogGen>;
    using ObjcType = GBLogGen*;

    using Boxed = LogGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

