// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import <Foundation/Foundation.h>
@class GBUiInjecterGen;
@protocol GBViewGroupGen;


@interface GBUiInjecterGen : NSObject

+ (nullable GBUiInjecterGen *)instance;

- (void)inject:(nonnull NSString *)id
     viewGroup:(nullable id<GBViewGroupGen>)viewGroup;

- (void)removeViewGroup:(nonnull NSString *)id;

- (void)getViewGroup:(nonnull NSString *)id;

@end
