// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "ui_injecter_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBUiInjecterGen;

namespace djinni_generated {

class UiInjecterGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::UiInjecterGen>;
    using CppOptType = std::shared_ptr<::gearsbox::UiInjecterGen>;
    using ObjcType = GBUiInjecterGen*;

    using Boxed = UiInjecterGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

