// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import <Foundation/Foundation.h>
@class GBUiInjecterGen;
@protocol GBViewGen;


@interface GBUiInjecterGen : NSObject

+ (nullable GBUiInjecterGen *)instance;

- (void)inject:(nonnull NSString *)id
          view:(nullable id<GBViewGen>)view;

- (nullable id<GBViewGen>)getView:(nonnull NSString *)id;

- (void)removeView:(nonnull NSString *)id;

@end
