// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewConstraint.h"
#include "view_constraint.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBViewConstraint;

namespace djinni_generated {

struct ViewConstraint
{
    using CppType = ::gearsbox::ViewConstraint;
    using ObjcType = GBViewConstraint*;

    using Boxed = ViewConstraint;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
