// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewGen+Private.h"
#import "GBViewGen.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "GBViewFrame+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class ViewGen::ObjcProxy final
: public ::gearsbox::ViewGen
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    std::string getId() override
    {
        @autoreleasepool {
            auto r = [Handle::get() getId];
            return ::djinni::String::toCpp(r);
        }
    }
    void setFrame(const ::gearsbox::ViewFrame & c_frame) override
    {
        @autoreleasepool {
            [Handle::get() setFrame:(::djinni_generated::ViewFrame::fromCpp(c_frame))];
        }
    }
    ::gearsbox::ViewFrame getFrame() override
    {
        @autoreleasepool {
            auto r = [Handle::get() getFrame];
            return ::djinni_generated::ViewFrame::toCpp(r);
        }
    }
    void setBackgroundColor(float c_a, float c_r, float c_g, float c_b) override
    {
        @autoreleasepool {
            [Handle::get() setBackgroundColor:(::djinni::F32::fromCpp(c_a))
                                            r:(::djinni::F32::fromCpp(c_r))
                                            g:(::djinni::F32::fromCpp(c_g))
                                            b:(::djinni::F32::fromCpp(c_b))];
        }
    }
    void setVisiable(bool c_v) override
    {
        @autoreleasepool {
            [Handle::get() setVisiable:(::djinni::Bool::fromCpp(c_v))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto ViewGen::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ViewGen::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
