// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewConstraint.h"


NSString * __nonnull const GBViewConstraintParent = @"parent";

@implementation GBViewConstraint

- (nonnull instancetype)initWithType:(GBConstraintType)type
                              typeTo:(GBConstraintType)typeTo
                            viewFrom:(nonnull NSString *)viewFrom
                              viewTo:(nonnull NSString *)viewTo
                          multiplier:(float)multiplier
                              offset:(float)offset
{
    if (self = [super init]) {
        _type = type;
        _typeTo = typeTo;
        _viewFrom = [viewFrom copy];
        _viewTo = [viewTo copy];
        _multiplier = multiplier;
        _offset = offset;
    }
    return self;
}

+ (nonnull instancetype)viewConstraintWithType:(GBConstraintType)type
                                        typeTo:(GBConstraintType)typeTo
                                      viewFrom:(nonnull NSString *)viewFrom
                                        viewTo:(nonnull NSString *)viewTo
                                    multiplier:(float)multiplier
                                        offset:(float)offset
{
    return [[self alloc] initWithType:type
                               typeTo:typeTo
                             viewFrom:viewFrom
                               viewTo:viewTo
                           multiplier:multiplier
                               offset:offset];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p type:%@ typeTo:%@ viewFrom:%@ viewTo:%@ multiplier:%@ offset:%@>", self.class, (void *)self, @(self.type), @(self.typeTo), self.viewFrom, self.viewTo, @(self.multiplier), @(self.offset)];
}

@end
