// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import <Foundation/Foundation.h>

@interface GBViewFrame : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y
                                w:(float)w
                                h:(float)h;
+ (nonnull instancetype)viewFrameWithX:(float)x
                                     y:(float)y
                                     w:(float)w
                                     h:(float)h;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@property (nonatomic, readonly) float w;

@property (nonatomic, readonly) float h;

@end
