// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewConstraint.h"
#import "GBViewFrame.h"
#import <Foundation/Foundation.h>
@protocol GBViewGen;


@protocol GBViewGen

- (void)setFrame:(nonnull GBViewFrame *)frame;

- (nonnull GBViewFrame *)getFrame;

- (void)setVisiable:(BOOL)v;

- (BOOL)addSubView:(nullable id<GBViewGen>)view;

- (void)addConstraint:(nonnull GBViewConstraint *)constraint;

@end
