// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewEventParam.h"


@implementation GBViewEventParam

- (nonnull instancetype)initWithX:(float)x
                                y:(float)y
                             type:(GBViewEvent)type
                             text:(nonnull NSString *)text
{
    if (self = [super init]) {
        _x = x;
        _y = y;
        _type = type;
        _text = [text copy];
    }
    return self;
}

+ (nonnull instancetype)viewEventParamWithX:(float)x
                                          y:(float)y
                                       type:(GBViewEvent)type
                                       text:(nonnull NSString *)text
{
    return [[self alloc] initWithX:x
                                 y:y
                              type:type
                              text:text];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p x:%@ y:%@ type:%@ text:%@>", self.class, (void *)self, @(self.x), @(self.y), @(self.type), self.text];
}

@end
