// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import <Foundation/Foundation.h>
@protocol GBViewGen;


@protocol GBViewGroupGen

- (nullable id<GBViewGen>)getView:(nonnull NSString *)id;

- (BOOL)addView:(nullable id<GBViewGen>)view;

- (BOOL)removeView:(nullable id<GBViewGen>)view;

@end
