// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewGen+Private.h"
#import "GBViewGen.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "GBViewConstraint+Private.h"
#import "GBViewFrame+Private.h"
#import "GBViewGen+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class ViewGen::ObjcProxy final
: public ::gearsbox::ViewGen
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void setFrame(const ::gearsbox::ViewFrame & c_frame) override
    {
        @autoreleasepool {
            [Handle::get() setFrame:(::djinni_generated::ViewFrame::fromCpp(c_frame))];
        }
    }
    ::gearsbox::ViewFrame getFrame() override
    {
        @autoreleasepool {
            auto r = [Handle::get() getFrame];
            return ::djinni_generated::ViewFrame::toCpp(r);
        }
    }
    void setVisiable(bool c_v) override
    {
        @autoreleasepool {
            [Handle::get() setVisiable:(::djinni::Bool::fromCpp(c_v))];
        }
    }
    bool addSubView(const std::shared_ptr<::gearsbox::ViewGen> & c_view) override
    {
        @autoreleasepool {
            auto r = [Handle::get() addSubView:(::djinni_generated::ViewGen::fromCpp(c_view))];
            return ::djinni::Bool::toCpp(r);
        }
    }
    void addConstraint(const ::gearsbox::ViewConstraint & c_constraint) override
    {
        @autoreleasepool {
            [Handle::get() addConstraint:(::djinni_generated::ViewConstraint::fromCpp(c_constraint))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto ViewGen::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ViewGen::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
