// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "view_group_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol GBViewGroupGen;

namespace djinni_generated {

class ViewGroupGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::ViewGroupGen>;
    using CppOptType = std::shared_ptr<::gearsbox::ViewGroupGen>;
    using ObjcType = id<GBViewGroupGen>;

    using Boxed = ViewGroupGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

