// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewEventParam.h"
#import <Foundation/Foundation.h>
@protocol GBViewGen;


@interface GBViewEventHandler : NSObject

- (BOOL)handle:(nonnull GBViewEventParam *)param
          view:(nullable id<GBViewGen>)view;

@end
