// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewConstraint.h"


@implementation GBViewConstraint

- (nonnull instancetype)initWithType:(GBConstraintType)type
                            viewFrom:(nonnull NSString *)viewFrom
                              viewTo:(nonnull NSString *)viewTo
                          multiplier:(int32_t)multiplier
                              offset:(int32_t)offset
{
    if (self = [super init]) {
        _type = type;
        _viewFrom = [viewFrom copy];
        _viewTo = [viewTo copy];
        _multiplier = multiplier;
        _offset = offset;
    }
    return self;
}

+ (nonnull instancetype)viewConstraintWithType:(GBConstraintType)type
                                      viewFrom:(nonnull NSString *)viewFrom
                                        viewTo:(nonnull NSString *)viewTo
                                    multiplier:(int32_t)multiplier
                                        offset:(int32_t)offset
{
    return [[self alloc] initWithType:type
                             viewFrom:viewFrom
                               viewTo:viewTo
                           multiplier:multiplier
                               offset:offset];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p type:%@ viewFrom:%@ viewTo:%@ multiplier:%@ offset:%@>", self.class, (void *)self, @(self.type), self.viewFrom, self.viewTo, @(self.multiplier), @(self.offset)];
}

@end
