// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "view_factory_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol GBViewFactoryGen;

namespace djinni_generated {

class ViewFactoryGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::ViewFactoryGen>;
    using CppOptType = std::shared_ptr<::gearsbox::ViewFactoryGen>;
    using ObjcType = id<GBViewFactoryGen>;

    using Boxed = ViewFactoryGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

