// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewFrame.h"
#include "view_frame.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBViewFrame;

namespace djinni_generated {

struct ViewFrame
{
    using CppType = ::gearsbox::ViewFrame;
    using ObjcType = GBViewFrame*;

    using Boxed = ViewFrame;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
