// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewConstraint.h"
#import "GBViewType.h"
#import <Foundation/Foundation.h>
@protocol GBViewGen;


@protocol GBViewGroupGen

- (nullable id<GBViewGen>)getView:(nonnull NSString *)id;

- (BOOL)addView:(nonnull NSString *)id
           type:(GBViewType)type;

- (BOOL)removeView:(nonnull NSString *)id;

- (void)addConstraint:(nonnull GBViewConstraint *)constraint;

@end
