// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBConstraintType.h"
#import <Foundation/Foundation.h>

@interface GBViewConstraint : NSObject
- (nonnull instancetype)initWithType:(GBConstraintType)type
                            viewFrom:(nonnull NSString *)viewFrom
                              viewTo:(nonnull NSString *)viewTo
                          multiplier:(int32_t)multiplier
                              offset:(int32_t)offset;
+ (nonnull instancetype)viewConstraintWithType:(GBConstraintType)type
                                      viewFrom:(nonnull NSString *)viewFrom
                                        viewTo:(nonnull NSString *)viewTo
                                    multiplier:(int32_t)multiplier
                                        offset:(int32_t)offset;

@property (nonatomic, readonly) GBConstraintType type;

@property (nonatomic, readonly, nonnull) NSString * viewFrom;

@property (nonatomic, readonly, nonnull) NSString * viewTo;

@property (nonatomic, readonly) int32_t multiplier;

@property (nonatomic, readonly) int32_t offset;

@end
