// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewEventParam+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ViewEventParam::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::F32::toCpp(obj.x),
            ::djinni::F32::toCpp(obj.y),
            ::djinni::Enum<::gearsbox::ViewEvent, GBViewEvent>::toCpp(obj.type),
            ::djinni::String::toCpp(obj.text)};
}

auto ViewEventParam::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[GBViewEventParam alloc] initWithX:(::djinni::F32::fromCpp(cpp.x))
                                             y:(::djinni::F32::fromCpp(cpp.y))
                                          type:(::djinni::Enum<::gearsbox::ViewEvent, GBViewEvent>::fromCpp(cpp.type))
                                          text:(::djinni::String::fromCpp(cpp.text))];
}

}  // namespace djinni_generated
