// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewFrame+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ViewFrame::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.x),
            ::djinni::I32::toCpp(obj.y),
            ::djinni::I32::toCpp(obj.w),
            ::djinni::I32::toCpp(obj.h)};
}

auto ViewFrame::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[GBViewFrame alloc] initWithX:(::djinni::I32::fromCpp(cpp.x))
                                        y:(::djinni::I32::fromCpp(cpp.y))
                                        w:(::djinni::I32::fromCpp(cpp.w))
                                        h:(::djinni::I32::fromCpp(cpp.h))];
}

}  // namespace djinni_generated
