// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewEventParam.h"
#include "view_event_param.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBViewEventParam;

namespace djinni_generated {

struct ViewEventParam
{
    using CppType = ::gearsbox::ViewEventParam;
    using ObjcType = GBViewEventParam*;

    using Boxed = ViewEventParam;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
