// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewFrame.h"
#import <Foundation/Foundation.h>


@protocol GBViewGen

- (nonnull NSString *)getId;

- (void)setFrame:(nonnull GBViewFrame *)frame;

- (nonnull GBViewFrame *)getFrame;

- (void)setBackgroundColor:(float)a
                         r:(float)r
                         g:(float)g
                         b:(float)b;

- (void)setVisiable:(BOOL)v;

@end
