// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace gearsbox {

class AsyncLoopGen {
public:
    virtual ~AsyncLoopGen() {}

    static std::shared_ptr<AsyncLoopGen> instance();

    virtual void process(int64_t elapse) = 0;
};

}  // namespace gearsbox
