// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <cstdint>
#include <string>

namespace gearsbox {

class CallbackHttpGen {
public:
    virtual ~CallbackHttpGen() {}

    virtual bool callback(int64_t id, bool result, const std::string & data) = 0;
};

}  // namespace gearsbox
