// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace gearsbox {

class LogGen {
public:
    virtual ~LogGen() {}

    static int32_t const LOG_CONSOLE;

    static int32_t const LOG_FILE;

    static int32_t const LOG_NET;

    static int32_t const LOG_VERBOSE;

    static int32_t const LOG_DEBUG;

    static int32_t const LOG_INFO;

    static int32_t const LOG_WARN;

    static int32_t const LOG_ERROR;

    static int32_t const LOG_FATAL;

    static std::shared_ptr<LogGen> instance();

    virtual bool initialize(int32_t output, const std::string & param) = 0;

    virtual void log(int32_t output, int32_t lev, const std::string & msg) = 0;
};

}  // namespace gearsbox
