// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "log_gen.hpp"  // my header

namespace gearsbox {

int32_t const LogGen::LOG_CONSOLE = 1;

int32_t const LogGen::LOG_FILE = 2;

int32_t const LogGen::LOG_NET = 4;

int32_t const LogGen::LOG_VERBOSE = 1;

int32_t const LogGen::LOG_DEBUG = 2;

int32_t const LogGen::LOG_INFO = 3;

int32_t const LogGen::LOG_WARN = 4;

int32_t const LogGen::LOG_ERROR = 5;

int32_t const LogGen::LOG_FATAL = 6;

}  // namespace gearsbox
