// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <memory>
#include <string>

namespace gearsbox {

class ViewGroupGen;

class UiInjecterGen {
public:
    virtual ~UiInjecterGen() {}

    static std::shared_ptr<UiInjecterGen> instance();

    virtual void inject(const std::string & id, const std::shared_ptr<ViewGroupGen> & view_group) = 0;

    virtual void removeViewGroup(const std::string & id) = 0;

    virtual void getViewGroup(const std::string & id) = 0;
};

}  // namespace gearsbox
