// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <memory>

namespace gearsbox {

struct ViewConstraint;
struct ViewFrame;

class ViewGen {
public:
    virtual ~ViewGen() {}

    virtual void setFrame(const ViewFrame & frame) = 0;

    virtual ViewFrame getFrame() = 0;

    virtual void setVisiable(bool v) = 0;

    virtual bool addSubView(const std::shared_ptr<ViewGen> & view) = 0;

    virtual void addConstraint(const ViewConstraint & constraint) = 0;
};

}  // namespace gearsbox
