// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <functional>

namespace gearsbox {

enum class ViewType : int {
    VIEW_BASE,
    VIEW_LABEL,
    VIEW_INPUT,
    VIEW_BTN,
};

}  // namespace gearsbox

namespace std {

template <>
struct hash<::gearsbox::ViewType> {
    size_t operator()(::gearsbox::ViewType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
