// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <memory>
#include <string>

namespace gearsbox {

class ViewGen;
enum class ViewType;
struct ViewConstraint;

class ViewGroupGen {
public:
    virtual ~ViewGroupGen() {}

    virtual std::shared_ptr<ViewGen> getView(const std::string & id) = 0;

    virtual bool addView(const std::string & id, ViewType type) = 0;

    virtual bool removeView(const std::string & id) = 0;

    virtual void addConstraint(const ViewConstraint & constraint) = 0;
};

}  // namespace gearsbox
