// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "view_event.hpp"
#include <string>
#include <utility>

namespace gearsbox {

struct ViewEventParam final {
    float x;
    float y;
    ViewEvent type;
    std::string text;

    ViewEventParam(float x_,
                   float y_,
                   ViewEvent type_,
                   std::string text_)
    : x(std::move(x_))
    , y(std::move(y_))
    , type(std::move(type_))
    , text(std::move(text_))
    {}
};

}  // namespace gearsbox
