// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace gearsbox {

struct ViewFrame final {
    int32_t x;
    int32_t y;
    int32_t w;
    int32_t h;

    ViewFrame(int32_t x_,
              int32_t y_,
              int32_t w_,
              int32_t h_)
    : x(std::move(x_))
    , y(std::move(y_))
    , w(std::move(w_))
    , h(std::move(h_))
    {}
};

}  // namespace gearsbox
