// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <memory>
#include <string>

namespace gearsbox {

class ViewGen;
enum class ViewType;

class ViewFactoryGen {
public:
    virtual ~ViewFactoryGen() {}

    virtual std::shared_ptr<ViewGen> createView(const std::string & id, ViewType type) = 0;
};

}  // namespace gearsbox
