// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <memory>
#include <string>

namespace gearsbox {

class ViewGen;

class ViewGroupGen {
public:
    virtual ~ViewGroupGen() {}

    virtual std::shared_ptr<ViewGen> getView(const std::string & id) = 0;

    virtual bool addView(const std::shared_ptr<ViewGen> & view) = 0;

    virtual bool removeView(const std::shared_ptr<ViewGen> & view) = 0;
};

}  // namespace gearsbox
