// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <utility>

namespace gearsbox {

struct ViewFrame final {
    float x;
    float y;
    float w;
    float h;

    ViewFrame(float x_,
              float y_,
              float w_,
              float h_)
    : x(std::move(x_))
    , y(std::move(y_))
    , w(std::move(w_))
    , h(std::move(h_))
    {}
};

}  // namespace gearsbox
