// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "view_constraint.hpp"  // my header

namespace gearsbox {

std::string const ViewConstraint::PARENT = {"parent"};

}  // namespace gearsbox
