// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "constraint_type.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace gearsbox {

struct ViewConstraint final {
    ConstraintType type;
    std::string view_from;
    std::string view_to;
    int32_t multiplier;
    int32_t offset;

    ViewConstraint(ConstraintType type_,
                   std::string view_from_,
                   std::string view_to_,
                   int32_t multiplier_,
                   int32_t offset_)
    : type(std::move(type_))
    , view_from(std::move(view_from_))
    , view_to(std::move(view_to_))
    , multiplier(std::move(multiplier_))
    , offset(std::move(offset_))
    {}
};

}  // namespace gearsbox
